figure(1)
plot(time_sf2_3,flux_sf2_3,'-')
xlabel('Time[s]')
ylabel('Flux')
title('SF2 starter-kit1')
figure(2)
plot(dose_sf2_3, lsram_sf2_3, '-')
xlabel('Dose[kRad]')
ylabel('SEU on LSRAM')
title('SF2 starter-kit1')
figure(3)
plot(dose_sf2_3, usram_sf2_3, '-')
xlabel('Dose[kRad]')
ylabel('SEU on uSRAM')
title('SF2 starter-kit1')
figure(4)
plot(time_sf2_4,flux_sf2_4,'-')
xlabel('Time[s]')
ylabel('Flux')
title('SF2 starter-kit2')
figure(5)
plot(dose_sf2_4, lsram_sf2_4, '-')
xlabel('Dose[kRad]')
ylabel('SEU on LSRAM')
title('SF2 starter-kit2')
figure(6)
plot(dose_sf2_4, usram_sf2_4, '-')
xlabel('Dose[kRad]')
ylabel('SEU on uSRAM')
title('SF2 starter-kit2')
figure(7)
plot(time_sf2_3,flux_sf2_3, time_sf2_4, flux_sf2_4,'m')
legend('SF2 starter-kit1', 'SF2 starter-kit2')
xlabel('Time[s]')
ylabel('Flux')
title('Flux for the different test boards')